"""empty message

Revision ID: 4fe29475cec1
Revises: a20e2a5129aa
Create Date: 2019-12-13 20:08:59.514269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fe29475cec1'
down_revision = 'a20e2a5129aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frecuencia de alimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frutas', sa.String(length=30), nullable=True),
    sa.Column('verduras', sa.String(length=30), nullable=True),
    sa.Column('carne', sa.String(length=30), nullable=True),
    sa.Column('lacteos', sa.String(length=30), nullable=True),
    sa.Column('agua', sa.String(length=30), nullable=True),
    sa.Column('gaseosa', sa.String(length=30), nullable=True),
    sa.Column('huevo', sa.String(length=30), nullable=True),
    sa.Column('cereales', sa.String(length=30), nullable=True),
    sa.Column('casera', sa.String(length=30), nullable=True),
    sa.Column('afuera', sa.String(length=30), nullable=True),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_frecuencia de alimentos_afuera'), 'frecuencia de alimentos', ['afuera'], unique=False)
    op.create_index(op.f('ix_frecuencia de alimentos_agua'), 'frecuencia de alimentos', ['agua'], unique=False)
    op.create_index(op.f('ix_frecuencia de alimentos_carne'), 'frecuencia de alimentos', ['carne'], unique=False)
    op.create_index(op.f('ix_frecuencia de alimentos_casera'), 'frecuencia de alimentos', ['casera'], unique=False)
    op.create_index(op.f('ix_frecuencia de alimentos_cereales'), 'frecuencia de alimentos', ['cereales'], unique=False)
    op.create_index(op.f('ix_frecuencia de alimentos_frutas'), 'frecuencia de alimentos', ['frutas'], unique=False)
    op.create_index(op.f('ix_frecuencia de alimentos_gaseosa'), 'frecuencia de alimentos', ['gaseosa'], unique=False)
    op.create_index(op.f('ix_frecuencia de alimentos_huevo'), 'frecuencia de alimentos', ['huevo'], unique=False)
    op.create_index(op.f('ix_frecuencia de alimentos_lacteos'), 'frecuencia de alimentos', ['lacteos'], unique=False)
    op.create_index(op.f('ix_frecuencia de alimentos_verduras'), 'frecuencia de alimentos', ['verduras'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_frecuencia de alimentos_verduras'), table_name='frecuencia de alimentos')
    op.drop_index(op.f('ix_frecuencia de alimentos_lacteos'), table_name='frecuencia de alimentos')
    op.drop_index(op.f('ix_frecuencia de alimentos_huevo'), table_name='frecuencia de alimentos')
    op.drop_index(op.f('ix_frecuencia de alimentos_gaseosa'), table_name='frecuencia de alimentos')
    op.drop_index(op.f('ix_frecuencia de alimentos_frutas'), table_name='frecuencia de alimentos')
    op.drop_index(op.f('ix_frecuencia de alimentos_cereales'), table_name='frecuencia de alimentos')
    op.drop_index(op.f('ix_frecuencia de alimentos_casera'), table_name='frecuencia de alimentos')
    op.drop_index(op.f('ix_frecuencia de alimentos_carne'), table_name='frecuencia de alimentos')
    op.drop_index(op.f('ix_frecuencia de alimentos_agua'), table_name='frecuencia de alimentos')
    op.drop_index(op.f('ix_frecuencia de alimentos_afuera'), table_name='frecuencia de alimentos')
    op.drop_table('frecuencia de alimentos')
    # ### end Alembic commands ###
