"""empty message

Revision ID: 54713688f19f
Revises: 
Create Date: 2019-12-11 16:53:25.968721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54713688f19f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=True),
    sa.Column('nacimiento', sa.Date(), nullable=True),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('telefono', sa.String(length=60), nullable=True),
    sa.Column('estado_civil', sa.String(length=60), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('cant_hijos', sa.Integer(), nullable=True),
    sa.Column('ocupacion', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pacientes_cant_hijos'), 'pacientes', ['cant_hijos'], unique=False)
    op.create_index(op.f('ix_pacientes_edad'), 'pacientes', ['edad'], unique=False)
    op.create_index(op.f('ix_pacientes_email'), 'pacientes', ['email'], unique=True)
    op.create_index(op.f('ix_pacientes_estado_civil'), 'pacientes', ['estado_civil'], unique=False)
    op.create_index(op.f('ix_pacientes_nombre'), 'pacientes', ['nombre'], unique=False)
    op.create_index(op.f('ix_pacientes_ocupacion'), 'pacientes', ['ocupacion'], unique=False)
    op.create_index(op.f('ix_pacientes_telefono'), 'pacientes', ['telefono'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pacientes_telefono'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_ocupacion'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_nombre'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_estado_civil'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_email'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_edad'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_cant_hijos'), table_name='pacientes')
    op.drop_table('pacientes')
    # ### end Alembic commands ###
