"""empty message

Revision ID: a20e2a5129aa
Revises: ad598f6da453
Create Date: 2019-12-13 17:18:35.060831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a20e2a5129aa'
down_revision = 'ad598f6da453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('antecedentes_familiares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diabetes', sa.String(length=30), nullable=True),
    sa.Column('cardiaca', sa.String(length=30), nullable=True),
    sa.Column('hipertension', sa.String(length=30), nullable=True),
    sa.Column('sobrepeso', sa.String(length=30), nullable=True),
    sa.Column('acv', sa.String(length=30), nullable=True),
    sa.Column('cancer', sa.String(length=30), nullable=True),
    sa.Column('observaciones', sa.String(length=60), nullable=True),
    sa.Column('otro_tca', sa.String(length=40), nullable=True),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_antecedentes_familiares_acv'), 'antecedentes_familiares', ['acv'], unique=False)
    op.create_index(op.f('ix_antecedentes_familiares_cancer'), 'antecedentes_familiares', ['cancer'], unique=False)
    op.create_index(op.f('ix_antecedentes_familiares_cardiaca'), 'antecedentes_familiares', ['cardiaca'], unique=False)
    op.create_index(op.f('ix_antecedentes_familiares_diabetes'), 'antecedentes_familiares', ['diabetes'], unique=False)
    op.create_index(op.f('ix_antecedentes_familiares_hipertension'), 'antecedentes_familiares', ['hipertension'], unique=False)
    op.create_index(op.f('ix_antecedentes_familiares_observaciones'), 'antecedentes_familiares', ['observaciones'], unique=False)
    op.create_index(op.f('ix_antecedentes_familiares_otro_tca'), 'antecedentes_familiares', ['otro_tca'], unique=False)
    op.create_index(op.f('ix_antecedentes_familiares_sobrepeso'), 'antecedentes_familiares', ['sobrepeso'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_antecedentes_familiares_sobrepeso'), table_name='antecedentes_familiares')
    op.drop_index(op.f('ix_antecedentes_familiares_otro_tca'), table_name='antecedentes_familiares')
    op.drop_index(op.f('ix_antecedentes_familiares_observaciones'), table_name='antecedentes_familiares')
    op.drop_index(op.f('ix_antecedentes_familiares_hipertension'), table_name='antecedentes_familiares')
    op.drop_index(op.f('ix_antecedentes_familiares_diabetes'), table_name='antecedentes_familiares')
    op.drop_index(op.f('ix_antecedentes_familiares_cardiaca'), table_name='antecedentes_familiares')
    op.drop_index(op.f('ix_antecedentes_familiares_cancer'), table_name='antecedentes_familiares')
    op.drop_index(op.f('ix_antecedentes_familiares_acv'), table_name='antecedentes_familiares')
    op.drop_table('antecedentes_familiares')
    # ### end Alembic commands ###
