"""empty message

Revision ID: ad598f6da453
Revises: c314f5ef0806
Create Date: 2019-12-13 16:06:17.365877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad598f6da453'
down_revision = 'c314f5ef0806'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_historia_personal_obs_alcohol', table_name='historia_personal')
    op.create_index(op.f('ix_historia_personal_obs_alcohol'), 'historia_personal', ['obs_alcohol'], unique=False)
    op.drop_index('ix_historia_personal_obs_alergias', table_name='historia_personal')
    op.create_index(op.f('ix_historia_personal_obs_alergias'), 'historia_personal', ['obs_alergias'], unique=False)
    op.drop_index('ix_historia_personal_obs_cirugias', table_name='historia_personal')
    op.create_index(op.f('ix_historia_personal_obs_cirugias'), 'historia_personal', ['obs_cirugias'], unique=False)
    op.drop_index('ix_historia_personal_obs_drogas', table_name='historia_personal')
    op.create_index(op.f('ix_historia_personal_obs_drogas'), 'historia_personal', ['obs_drogas'], unique=False)
    op.drop_index('ix_historia_personal_obs_enf_cron', table_name='historia_personal')
    op.create_index(op.f('ix_historia_personal_obs_enf_cron'), 'historia_personal', ['obs_enf_cron'], unique=False)
    op.drop_index('ix_historia_personal_obs_med_psiquiatrica', table_name='historia_personal')
    op.create_index(op.f('ix_historia_personal_obs_med_psiquiatrica'), 'historia_personal', ['obs_med_psiquiatrica'], unique=False)
    op.drop_index('ix_historia_personal_obs_otra_med', table_name='historia_personal')
    op.create_index(op.f('ix_historia_personal_obs_otra_med'), 'historia_personal', ['obs_otra_med'], unique=False)
    op.drop_index('ix_historia_personal_obs_tabaco', table_name='historia_personal')
    op.create_index(op.f('ix_historia_personal_obs_tabaco'), 'historia_personal', ['obs_tabaco'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historia_personal_obs_tabaco'), table_name='historia_personal')
    op.create_index('ix_historia_personal_obs_tabaco', 'historia_personal', ['obs_tabaco'], unique=True)
    op.drop_index(op.f('ix_historia_personal_obs_otra_med'), table_name='historia_personal')
    op.create_index('ix_historia_personal_obs_otra_med', 'historia_personal', ['obs_otra_med'], unique=True)
    op.drop_index(op.f('ix_historia_personal_obs_med_psiquiatrica'), table_name='historia_personal')
    op.create_index('ix_historia_personal_obs_med_psiquiatrica', 'historia_personal', ['obs_med_psiquiatrica'], unique=True)
    op.drop_index(op.f('ix_historia_personal_obs_enf_cron'), table_name='historia_personal')
    op.create_index('ix_historia_personal_obs_enf_cron', 'historia_personal', ['obs_enf_cron'], unique=True)
    op.drop_index(op.f('ix_historia_personal_obs_drogas'), table_name='historia_personal')
    op.create_index('ix_historia_personal_obs_drogas', 'historia_personal', ['obs_drogas'], unique=True)
    op.drop_index(op.f('ix_historia_personal_obs_cirugias'), table_name='historia_personal')
    op.create_index('ix_historia_personal_obs_cirugias', 'historia_personal', ['obs_cirugias'], unique=True)
    op.drop_index(op.f('ix_historia_personal_obs_alergias'), table_name='historia_personal')
    op.create_index('ix_historia_personal_obs_alergias', 'historia_personal', ['obs_alergias'], unique=True)
    op.drop_index(op.f('ix_historia_personal_obs_alcohol'), table_name='historia_personal')
    op.create_index('ix_historia_personal_obs_alcohol', 'historia_personal', ['obs_alcohol'], unique=True)
    # ### end Alembic commands ###
