"""empty message

Revision ID: c314f5ef0806
Revises: 54713688f19f
Create Date: 2019-12-13 15:22:35.247577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c314f5ef0806'
down_revision = '54713688f19f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historia_personal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enfermedades_cronicas', sa.String(length=5), nullable=True),
    sa.Column('obs_enf_cron', sa.String(length=60), nullable=True),
    sa.Column('cirugias', sa.String(length=5), nullable=True),
    sa.Column('obs_cirugias', sa.String(length=60), nullable=True),
    sa.Column('alergias', sa.String(length=5), nullable=True),
    sa.Column('obs_alergias', sa.String(length=60), nullable=True),
    sa.Column('med_psiquiatrica', sa.String(length=5), nullable=True),
    sa.Column('obs_med_psiquiatrica', sa.String(length=60), nullable=True),
    sa.Column('otra_med', sa.String(length=5), nullable=True),
    sa.Column('obs_otra_med', sa.String(length=60), nullable=True),
    sa.Column('tabaco', sa.String(length=5), nullable=True),
    sa.Column('obs_tabaco', sa.String(length=60), nullable=True),
    sa.Column('alcohol', sa.String(length=5), nullable=True),
    sa.Column('obs_alcohol', sa.String(length=60), nullable=True),
    sa.Column('drogas', sa.String(length=5), nullable=True),
    sa.Column('obs_drogas', sa.String(length=60), nullable=True),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historia_personal_alcohol'), 'historia_personal', ['alcohol'], unique=False)
    op.create_index(op.f('ix_historia_personal_alergias'), 'historia_personal', ['alergias'], unique=False)
    op.create_index(op.f('ix_historia_personal_cirugias'), 'historia_personal', ['cirugias'], unique=False)
    op.create_index(op.f('ix_historia_personal_drogas'), 'historia_personal', ['drogas'], unique=False)
    op.create_index(op.f('ix_historia_personal_enfermedades_cronicas'), 'historia_personal', ['enfermedades_cronicas'], unique=False)
    op.create_index(op.f('ix_historia_personal_med_psiquiatrica'), 'historia_personal', ['med_psiquiatrica'], unique=False)
    op.create_index(op.f('ix_historia_personal_obs_alcohol'), 'historia_personal', ['obs_alcohol'], unique=True)
    op.create_index(op.f('ix_historia_personal_obs_alergias'), 'historia_personal', ['obs_alergias'], unique=True)
    op.create_index(op.f('ix_historia_personal_obs_cirugias'), 'historia_personal', ['obs_cirugias'], unique=True)
    op.create_index(op.f('ix_historia_personal_obs_drogas'), 'historia_personal', ['obs_drogas'], unique=True)
    op.create_index(op.f('ix_historia_personal_obs_enf_cron'), 'historia_personal', ['obs_enf_cron'], unique=True)
    op.create_index(op.f('ix_historia_personal_obs_med_psiquiatrica'), 'historia_personal', ['obs_med_psiquiatrica'], unique=True)
    op.create_index(op.f('ix_historia_personal_obs_otra_med'), 'historia_personal', ['obs_otra_med'], unique=True)
    op.create_index(op.f('ix_historia_personal_obs_tabaco'), 'historia_personal', ['obs_tabaco'], unique=True)
    op.create_index(op.f('ix_historia_personal_otra_med'), 'historia_personal', ['otra_med'], unique=False)
    op.create_index(op.f('ix_historia_personal_tabaco'), 'historia_personal', ['tabaco'], unique=False)
    op.add_column('pacientes', sa.Column('observaciones', sa.String(length=60), nullable=True))
    op.create_index(op.f('ix_pacientes_observaciones'), 'pacientes', ['observaciones'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pacientes_observaciones'), table_name='pacientes')
    op.drop_column('pacientes', 'observaciones')
    op.drop_index(op.f('ix_historia_personal_tabaco'), table_name='historia_personal')
    op.drop_index(op.f('ix_historia_personal_otra_med'), table_name='historia_personal')
    op.drop_index(op.f('ix_historia_personal_obs_tabaco'), table_name='historia_personal')
    op.drop_index(op.f('ix_historia_personal_obs_otra_med'), table_name='historia_personal')
    op.drop_index(op.f('ix_historia_personal_obs_med_psiquiatrica'), table_name='historia_personal')
    op.drop_index(op.f('ix_historia_personal_obs_enf_cron'), table_name='historia_personal')
    op.drop_index(op.f('ix_historia_personal_obs_drogas'), table_name='historia_personal')
    op.drop_index(op.f('ix_historia_personal_obs_cirugias'), table_name='historia_personal')
    op.drop_index(op.f('ix_historia_personal_obs_alergias'), table_name='historia_personal')
    op.drop_index(op.f('ix_historia_personal_obs_alcohol'), table_name='historia_personal')
    op.drop_index(op.f('ix_historia_personal_med_psiquiatrica'), table_name='historia_personal')
    op.drop_index(op.f('ix_historia_personal_enfermedades_cronicas'), table_name='historia_personal')
    op.drop_index(op.f('ix_historia_personal_drogas'), table_name='historia_personal')
    op.drop_index(op.f('ix_historia_personal_cirugias'), table_name='historia_personal')
    op.drop_index(op.f('ix_historia_personal_alergias'), table_name='historia_personal')
    op.drop_index(op.f('ix_historia_personal_alcohol'), table_name='historia_personal')
    op.drop_table('historia_personal')
    # ### end Alembic commands ###
